package top.aiome.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTravel<M extends BaseTravel<M>> extends Model<M> implements IBean {

	public void setTrivalId(java.lang.Integer trivalId) {
		set("trivalId", trivalId);
	}

	public java.lang.Integer getTrivalId() {
		return get("trivalId");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setGuiderId(java.lang.Integer guiderId) {
		set("guiderId", guiderId);
	}

	public java.lang.Integer getGuiderId() {
		return get("guiderId");
	}

	public void setSchoolId(java.lang.Integer schoolId) {
		set("schoolId", schoolId);
	}

	public java.lang.Integer getSchoolId() {
		return get("schoolId");
	}

	public void setTrivalTime(java.lang.String trivalTime) {
		set("trivalTime", trivalTime);
	}

	public java.lang.String getTrivalTime() {
		return get("trivalTime");
	}

}
