package top.aiome.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserCommon<M extends BaseUserCommon<M>> extends Model<M> implements IBean {

	public void setCommonId(java.lang.Integer commonId) {
		set("commonId", commonId);
	}

	public java.lang.Integer getCommonId() {
		return get("commonId");
	}

	public void setGuiderId(java.lang.Integer guiderId) {
		set("guiderId", guiderId);
	}

	public java.lang.Integer getGuiderId() {
		return get("guiderId");
	}

	public void setCommon(java.lang.String common) {
		set("common", common);
	}

	public java.lang.String getCommon() {
		return get("common");
	}

	public void setScore(java.lang.String score) {
		set("score", score);
	}

	public java.lang.String getScore() {
		return get("score");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

}
