package top.aiome.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSchoolCommon<M extends BaseSchoolCommon<M>> extends Model<M> implements IBean {

	public void setCommonId(java.lang.Integer commonId) {
		set("commonId", commonId);
	}

	public java.lang.Integer getCommonId() {
		return get("commonId");
	}

	public void setSchoolId(java.lang.Integer schoolId) {
		set("schoolId", schoolId);
	}

	public java.lang.Integer getSchoolId() {
		return get("schoolId");
	}

	public void setCommon(java.lang.String common) {
		set("common", common);
	}

	public java.lang.String getCommon() {
		return get("common");
	}

	public void setScore(java.lang.String score) {
		set("score", score);
	}

	public java.lang.String getScore() {
		return get("score");
	}

	public void setImage(java.lang.String image) {
		set("image", image);
	}

	public java.lang.String getImage() {
		return get("image");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

}
