package top.aiome.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMatched<M extends BaseMatched<M>> extends Model<M> implements IBean {

	public void setMatchId(java.lang.Integer matchId) {
		set("matchId", matchId);
	}

	public java.lang.Integer getMatchId() {
		return get("matchId");
	}

	public void setGuiderId(java.lang.Integer guiderId) {
		set("guiderId", guiderId);
	}

	public java.lang.Integer getGuiderId() {
		return get("guiderId");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setFlag(java.lang.Boolean flag) {
		set("flag", flag);
	}

	public java.lang.Boolean getFlag() {
		return get("flag");
	}

	public void setCurrent(java.lang.String current) {
		set("current", current);
	}

	public java.lang.String getCurrent() {
		return get("current");
	}

}
