package top.aiome.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("blog", "id", Blog.class);
		arp.addMapping("college", "coid", College.class);
		arp.addMapping("major", "scid", Major.class);
		arp.addMapping("matched", "matchId", Matched.class);
		arp.addMapping("province", "pid", Province.class);
		arp.addMapping("school_common", "commonId", SchoolCommon.class);
		arp.addMapping("sms", "smsId", Sms.class);
		arp.addMapping("travel", "trivalId", Travel.class);
		arp.addMapping("user", "userId", User.class);
		arp.addMapping("user_common", "commonId", UserCommon.class);
	}
}

