package top.aiome.common.model;

import top.aiome.common.model.base.BaseMatched;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Matched extends BaseMatched<Matched> {
	public static final Matched dao = new Matched();
}
