package top.aiome.common.model;

import top.aiome.common.model.base.BaseSchoolCommon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SchoolCommon extends BaseSchoolCommon<SchoolCommon> {
	public static final SchoolCommon dao = new SchoolCommon();
}
