package top.aiome.common.model;

import top.aiome.common.model.base.BaseUserCommon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserCommon extends BaseUserCommon<UserCommon> {
	public static final UserCommon dao = new UserCommon();
}
